### PR TITLE
[OE] Generalized token verification

### LINKED ISSUE #324: [OE] GetData Endpoint Application Validation
### Describe the Bug

Currently, the auth is tied to Choreo Implementation where custom claims are being obtained, But the real implementation should be generic to any API Gateway.

This is how the generic decoded token looks like.

Image

### To Reproduce

1. Create an M2M Application in Asgardeo / Identity Server.
2. Visit the website[Token Validation](https://fusionauth.io/dev-tools/jwt-decoder) and decode the token.

### Expected Behavior

1. Each App should be uniquely identified by its `client_id`.

### Screenshots

_No response_

### Version

v0.0.2

### Environment Details (with versions)

_No response_

### Additional Context

_No response_

### LINKED ISSUE #406: [OE] Introduce Configuration driven Signature Verification
### Current Limitation

The orchestration engine currently accepts generic M2M tokens but parses them **without signature verification** (`ParseUnverified`). It relies entirely on the upstream API Gateway to validate the token signature. There is no mechanism within the engine to enforce signature validation, meaning if the engine is accessed directly (bypassing the gateway) or if the gateway is misconfigured, invalid or forged tokens could be accepted.

### Suggested Improvement

Introduce a configuration-driven approach to optionally enforce signature verification:
- Add a `trust_api_gateway` boolean flag to `config.json` (default: `true`).
- Add a `jwks_url` string to `config.json` to specify the IdP's JSON Web Key Set URL.
- Modify [GetConsumerJwtFromToken](cci:1://file:///Users/thanikan-s/GitHub/opendif-core/exchange/orchestration-engine/auth/token.go:11:0-114:1):
  - If `trust_api_gateway` is `true`, continue with the current behavior (trust the gateway).
  - If `trust_api_gateway` is `false`, fetch the public keys from `jwks_url` and strictly **verify the JWT signature** before accepting the token.

### Version

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sthanikan2000**
## Summary
This PR enhances the token validation logic in the orchestration engine to support standard OIDC/OAuth2 claims with security-focused validation. It replaces unverified token parsing with mandatory claim validation, JWKS-based signature verification support, and configuration-driven issuer/audience validation.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [x] Refactoring (no functional changes)
- [ ] Performance improvement
- [ ] Other (please describe):

### Security Enhancements
- **Mandatory `exp` (expiration) validation**: Tokens without a valid expiration claim are now rejected
- **Issuer (`iss`) validation**: When configured, validates token issuer matches `ExpectedIssuer`
- **Audience (`aud`) validation**: When configured, validates token audience matches one of `ValidAudiences`
- **JWKS-based signature verification**: When `JwksUrl` is configured, enforces cryptographic signature verification (optional fallback to unverified parsing if not configured)

### Configuration Changes
- Added `JWTConfig` struct to `configs/config.go` with fields:
  - `ExpectedIssuer` (optional): Expected issuer claim value
  - `ValidAudiences` (optional): List of valid audience values
  - `JwksUrl` (optional): URL to fetch JWKS for signature verification
- Added `JWT` field to main `Config` struct for configuration loading

### Token Validation Logic (`auth/token.go`)
- Updated `GetConsumerJwtFromToken()` to accept `*configs.JWTConfig` parameter
- Implements standard JWT claim extraction for: `iss`, `aud`, `exp`, `nbf`, `iat`, `client_id`, `sub`, `azp`
- Validates claims in order of security importance:
  1. Token signature (if JWKS configured)
  2. Expiration (`exp`) - **mandatory**
  3. Not-before (`nbf`) - optional check
  4. Client ID - required
  5. Issuer (`iss`) - validated if configured
  6. Audience (`aud`) - validated if configured
- Supports both string and array formats for `aud` claim

### Server Integration (`server/server.go`)
- Updated call to `GetConsumerJwtFromToken()` to pass JWT configuration from `f.Configs.JWT`

## Testing
- [x] All 13 unit tests pass (7 existing + 5 new)
- [x] Tests cover valid/invalid scenarios for:
  - Missing `exp` claim (mandatory validation)
  - Issuer validation (valid and invalid)
  - Audience validation (valid and invalid)
  - All existing token extraction scenarios
- [x] Edge cases tested (missing claims, multiple audiences, etc.)
- [x] Server build verification

## Checklist
- [x] My code follows the project's style guidelines
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have verified all tests pass
- [x] No breaking changes to public API (configuration is backward compatible)

## Related Issues
Closes #324
Closes #406 

### Validation Flow
```
Token Extraction → Signature Verification (if JWKS configured) 
→ Mandatory Claims (exp, client_id) 
→ Optional Claims (iss, aud - validated if configured)
→ Return ConsumerAssertion with extracted claims
```

### Configuration Example
```json
{
  "jwt": {
    "expectedIssuer": "https://idp.example.com",
    "validAudiences": ["https://api.example.com", "https://api2.example.com"],
    "jwksUrl": "https://idp.example.com/.well-known/jwks.json"
  }
}
```

### Backward Compatibility
- Configuration fields are optional
- Missing configuration defaults to unverified parsing (legacy behavior)
- When configuration is provided, validation is enforced
- All validation errors are explicit with clear error messages

## Deployment Notes
- Recommended: Configure `JwksUrl` for signature verification in production
- Issuer and audience validation are optional but recommended for security
- Update configuration files with JWT validation settings before deployment

### CODE REVIEW

File: exchange/orchestration-engine/auth/token.go [hunk 1]
```diff
@@ -3,67 +3,229 @@ package auth
...
+				return nil, fmt.Errorf("failed to create JWKS from URL: %w", err)
+			}
 
-	// Parse without validation (only safe if API gateway already validated it!)
-	token, _, err := jwt.NewParser().ParseUnverified(tokenString, jwt.MapClaims{})
-	if err != nil {
-		return nil, fmt.Errorf("failed to parse token: %w", err)
+			token, err = jwt.Parse(tokenString, jwks.Keyfunc)
+			if err != nil {
+				return nil, fmt.Errorf("failed to parse and verify token: %w", err)
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: nit: separate the check whether failed to parse or failed to verify token. 

Suggest: 
```go
token, err = jwt.Parse(tokenString, jwks.Keyfunc)
if err != nil {
    var validationErr *jwt.ValidationError
    if errors.As(err, &validationErr) {
        if validationErr.Errors&jwt.ValidationErrorSignatureInvalid != 0 {
            return nil, fmt.Errorf("token signature verification failed: %w", err)
        }
        if validationErr.Errors&jwt.ValidationErrorMalformed != 0 {
            return nil, fmt.Errorf("malformed token: %w", err)
        }
    }
    return nil, fmt.Errorf("failed to parse token: %w", err)
}
```

File: exchange/orchestration-engine/auth/token.go [hunk 2]
```diff
@@ -3,67 +3,229 @@ package auth
...
 	}
 
-	// Map claims into struct
+	// Capture current time once for all temporal validations
+	now := time.Now().Unix()
+
+	// Validate generic claims
+	// exp is mandatory
+	exp, ok := claims[ClaimExp].(float64)
+	if !ok || exp == 0 {
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: 0 is valid timestamp, the check here could reject valid tokens and accept invalid ones. suggest more robust check:

```go
expVal, exists := claims[ClaimExp]
if !exists {
    return nil, fmt.Errorf("missing exp claim")
}
exp, ok := expVal.(float64)
if !ok {
    return nil, fmt.Errorf("invalid exp claim type: expected number, got %T", expVal)
}
// Note: exp can be 0 (epoch), so only check if it's negative
if exp < 0 {
    return nil, fmt.Errorf("invalid exp claim value: cannot be negative")
}
```

File: exchange/orchestration-engine/auth/token.go [hunk 3]
```diff
@@ -3,67 +3,229 @@ package auth
...
+	}
+
+	// client_id is required
+	clientId, ok := claims[ClaimClientId].(string)
+	if !ok || clientId == "" {
+		return nil, fmt.Errorf("missing or invalid client_id claim")
+	}
+
+	// sub or azp
+	subscriber, ok := claims[ClaimSub].(string)
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: problem here is subscriber can be empty without validation. Suggest: 


```go
subscriber, ok := claims[ClaimSub].(string)
if !ok || subscriber == "" {
    if azp, ok := claims[ClaimAzp].(string); ok && azp != "" {
        subscriber = azp
    }
}
if subscriber == "" {
    return nil, fmt.Errorf("missing subscriber claim: both 'sub' and 'azp' are missing or empty")
}
```

File: exchange/orchestration-engine/auth/token.go [hunk 4]
```diff
@@ -3,67 +3,229 @@ package auth
...
+
+	var token *jwt.Token
+	var err error
+	if trustUpstream {
+		// If we trust upstream, we assume the token has been validated already
+		token, _, err = jwt.NewParser().ParseUnverified(tokenString, jwt.MapClaims{})
+		if err != nil {
+			return nil, fmt.Errorf("failed to parse token: %w", err)
+		}
+	} else {
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: double check this but it seems JWKS is created on every request (lines 119-134) when the validator is missing/mismatched

suggest: remove the fallback. If `trustUpstream` is false, require a properly initialized `TokenValidator`:
```go
if !trustUpstream {
    if validator == nil || validator.jwksURL != jwtConfig.JwksUrl {
        return nil, fmt.Errorf("TokenValidator required when trustUpstream is false")
    }
    token, err = validator.validateSignature(tokenString)
}

**Review by ginaxu1 — CHANGES_REQUESTED** [review]

File: exchange/orchestration-engine/auth/token.go [hunk 5]
```diff
@@ -1,70 +1,417 @@
...
+	jwks    keyfunc.Keyfunc
+	jwksURL string
+}
 
-	ClaimSubscriber = WSO2ClaimPrefix + "subscriber"
-	ClaimAppUUID    = WSO2ClaimPrefix + "applicationUUId"
-	ClaimAppID      = WSO2ClaimPrefix + "applicationid"
-)
+// fetchAndFilterJWKS fetches JWKS from URL and removes keys with x5c certificates to avoid parsing errors
+func fetchAndFilterJWKS(jwksURL string) (json.RawMessage, error) {
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: make this function context-aware so user can cancel long-running JWKS fetches


   ```go
   func fetchAndFilterJWKS(ctx context.Context, jwksURL string) (json.RawMessage, error) {
       req, err := http.NewRequestWithContext(ctx, http.MethodGet, jwksURL, nil)
       if err != nil {
           return nil, fmt.Errorf("failed to create request: %w", err)
       }
       resp, err := httpClient.Do(req)
       // ...
   }
   ```

File: exchange/orchestration-engine/auth/token.go [hunk 6]
```diff
@@ -1,70 +1,417 @@
...
+	if skippedCount > 0 {
+		log.Printf("Filtered %d key(s) with x5c certificates from JWKS", skippedCount)
+	}
+
+	jwks["keys"] = filteredKeys
+	return json.Marshal(jwks)
+}
+
+// NewTokenValidator creates a new TokenValidator instance with auto-refresh
+func NewTokenValidator(jwksURL string) (*TokenValidator, error) {
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: `NewTokenValidator` is synchronously fetching JWKS during init. can block application startup if the JWKS endpoint is slow or unavailable.

double check you implemented lazy initialization with background refresh OR look into`keyfunc.NewJWKSetJSON` with auto-refresh (if library supports): 
   ```go
   // Check if keyfunc supports auto-refresh
   jwks, err := keyfunc.NewJWKSetJSON(jwksJSON, keyfunc.Options{
       RefreshInterval: 15 * time.Minute,
       RefreshErrorHandler: func(err error) {
           logger.Log.Warn("JWKS refresh failed", "error", err)
       },
   })
   ```

File: exchange/orchestration-engine/auth/token.go [hunk 7]
```diff
@@ -1,70 +1,417 @@
...
+		jwksURL: jwksURL,
+	}, nil
+}
+
+// validateSignature validates the token signature using cached JWKS
+func (v *TokenValidator) validateSignature(tokenString string) (*jwt.Token, error) {
+	token, err := jwt.Parse(tokenString, v.jwks.Keyfunc)
+	if err != nil {
+		// Provide more specific error messages based on error content
+		errMsg := err.Error()
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: nit: you're relying on string matching, which is fragile and may break with library updates.

better to either 1. wrap errors and check with `errors.Is()` or `errors.As()` or 2. use type assertions or error wrapping to check error types:
   ```go
   var jwtErr *jwt.ValidationError
   if errors.As(err, &jwtErr) {
       switch jwtErr.Errors {
       case jwt.ValidationErrorSignatureInvalid:
           return nil, fmt.Errorf("token signature verification failed: %w", err)
       case jwt.ValidationErrorMalformed:
           return nil, fmt.Errorf("malformed token: %w", err)
       }
   }
   ```

File: exchange/orchestration-engine/auth/token.go [hunk 8]
```diff
@@ -1,70 +1,417 @@
...
+	jwks["keys"] = filteredKeys
+	return json.Marshal(jwks)
+}
+
+// NewTokenValidator creates a new TokenValidator instance with auto-refresh
+func NewTokenValidator(jwksURL string) (*TokenValidator, error) {
+	if jwksURL == "" {
+		return &TokenValidator{}, nil
+	}
+
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: missing validation of JWKS URL format before attempting to fetch (before line 111). suggest:
```go
    
    // Validate URL format before attempting to fetch
    parsedURL, err := url.Parse(jwksURL)
    if err != nil {
        return nil, fmt.Errorf("invalid JWKS URL format: %w", err)
    }

    // Validate URL scheme
    if parsedURL.Scheme != "http" && parsedURL.Scheme != "https" {
        return nil, fmt.Errorf("invalid JWKS URL scheme: expected http or https, got %s", parsedURL.Scheme)
    }

    // Warn if not using HTTPS (security best practice)
    if parsedURL.Scheme != "https" {
        logger.Log.Warn("JWKS URL does not use HTTPS", "jwksUrl", jwksURL)
    }

    // Validate URL has a host
    if parsedURL.Host == "" {
        return nil, fmt.Errorf("invalid JWKS URL: missing host")
    }
```

File: exchange/orchestration-engine/auth/token.go [hunk 9]
```diff
@@ -1,70 +1,417 @@
...
+}
+
+// GetConsumerJwtFromToken validates and parses JWT token from HTTP request
+func GetConsumerJwtFromToken(env string, jwtConfig *configs.JWTConfig, trustUpstream bool, r *http.Request) (*ConsumerAssertion, error) {
+	return GetConsumerJwtFromTokenWithValidator(env, jwtConfig, trustUpstream, r, nil)
+}
+
+// GetConsumerJwtFromTokenWithValidator validates and parses JWT token with optional cached validator
+func GetConsumerJwtFromTokenWithValidator(env string, jwtConfig *configs.JWTConfig, trustUpstream bool, r *http.Request, validator *TokenValidator) (*ConsumerAssertion, error) {
+	if env == "development" {
```
[the remark this answers is not in the document]
Comment (ginaxu1) [reply exchange/orchestration-engine/auth/token.go]: Got it, keep okay. thanks for clarifying

File: exchange/orchestration-engine/auth/token.go [hunk 10]
```diff
@@ -1,70 +1,566 @@
...
+}
+
+// validateSignature validates the token signature using cached JWKS
+func (v *TokenValidator) validateSignature(tokenString string) (*jwt.Token, error) {
+	token, err := jwt.Parse(tokenString, v.jwks.Keyfunc)
+	if err != nil {
+		// Use error type checking for more robust error handling instead of string matching
+		switch {
+		case errors.Is(err, jwt.ErrTokenSignatureInvalid):
+			return nil, fmt.Errorf("token signature verification failed (JWKS URL: %s): %w", v.jwksURL, err)
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: Are you sure we want to expose jwksURL in the error message? same with lines 292, 294

Better to keep generic

```go
// Don't expose JWKS URL in error messages returned to clients
case errors.Is(err, jwt.ErrTokenSignatureInvalid):
    return nil, fmt.Errorf("token signature verification failed: %w", err)
case errors.Is(err, jwt.ErrTokenUnverifiable):
    return nil, fmt.Errorf("token key not found in JWKS: %w", err)
default:
    return nil, fmt.Errorf("failed to parse and verify token: %w", err)
```

File: exchange/orchestration-engine/auth/token.go [hunk 11]
```diff
@@ -1,70 +1,566 @@
...
+
+// TokenValidator handles JWT token validation with auto-refreshing JWKS.
+// The JWKS is automatically refreshed in the background to handle key rotation.
+type TokenValidator struct {
+	jwks    keyfunc.Keyfunc // Keyfunc with background refresh goroutine
+	jwksURL string
+}
+
+// fetchAndFilterJWKS fetches JWKS from URL and removes keys with x5c certificates to avoid parsing errors
+func fetchAndFilterJWKS(ctx context.Context, jwksURL string) (json.RawMessage, error) {
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: nit: missing Hostname Validation for JWKS URL

```go
// Validate hostname format
hostname := parsedURL.Hostname()
if hostname == "" {
    return nil, fmt.Errorf("invalid JWKS URL: missing hostname")
}

// Check for URL encoding attacks
if strings.Contains(hostname, "%") {
    return nil, fmt.Errorf("invalid JWKS URL: encoded characters in hostname")
}

// Validate hostname doesn't contain invalid characters
if strings.ContainsAny(hostname, " \t\n\r") {
    return nil, fmt.Errorf("invalid JWKS URL: invalid characters in hostname")
}
```

File: exchange/orchestration-engine/auth/token.go [hunk 12]
```diff
@@ -1,70 +1,566 @@
...
+//  3. High availability during key rotation periods
+//  4. No x5c certificate parsing errors
+func NewTokenValidator(ctx context.Context, jwksURL string) (*TokenValidator, error) {
+	if jwksURL == "" {
+		return &TokenValidator{}, nil
+	}
+
+	// First, validate and fetch JWKS to ensure fail-fast behavior
+	// This ensures the service won't start with an invalid JWKS URL
+	fetchCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: you're creating new `context.Background()` instead of using the provided `ctx` parameter. suggest:


```go
// Use parent ctx with timeout
fetchCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
defer cancel()
```

**Review by ginaxu1 — APPROVED** [review]

File: exchange/orchestration-engine/auth/token.go [hunk 13]
```diff
@@ -1,70 +1,570 @@
...
+// TokenValidator handles JWT token validation with auto-refreshing JWKS.
+// The JWKS is automatically refreshed in the background to handle key rotation.
+type TokenValidator struct {
+	jwks    keyfunc.Keyfunc // Keyfunc with background refresh goroutine
+	jwksURL string
+}
+
+// fetchAndFilterJWKS fetches JWKS from URL and removes keys with x5c certificates to avoid parsing errors
+func fetchAndFilterJWKS(ctx context.Context, jwksURL string) (json.RawMessage, error) {
+	// Validate URL format before attempting to fetch
```
Comment (ginaxu1) [inline exchange/orchestration-engine/auth/token.go]: nit: add check here for where the URL points (private networks vs. public internet). currently HTTP client will NOT reject private IPs, so an attacker could control the JWKS URL (via config injection, env variable manipulation). suggest additional checks:

```go
import (
    "net"
    "strings"
)

// Add hostname/IP validation
func isPrivateIP(host string) bool {
    ip := net.ParseIP(host)
    if ip == nil {
        return false
    }
    return ip.IsLoopback() || ip.IsPrivate() || ip.IsLinkLocalUnicast()
}

// In fetchAndFilterJWKS (after line 138):
hostname := parsedURL.Hostname()
if isPrivateIP(hostname) {
    return nil, fmt.Errorf("JWKS URL cannot point to private/internal network")
}

// Block cloud metadata endpoints
if strings.Contains(hostname, "169.254.169.254") {
    return nil, fmt.Errorf("JWKS URL cannot point to cloud metadata endpoint")
}
```

**Review by ginaxu1 — CHANGES_REQUESTED** [review]
